extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.11", import: ["@key", "@external", "@shareable"])

type CheckoutOperation @key(fields: "id") {
  id: ID!
  operationKey: ID!
  status: CheckoutStatus!
}

extend type Order @key(fields: "wooOrderId") {
  wooOrderId: ID! @external @shareable
  workflow: OrderWorkflow!
  pixCode: String
}

extend type Cart @key(fields: "id") {
  id: ID! @external
}

type OrderWorkflow {
  state: WorkflowState!
}

enum CheckoutStatus {
  PENDING
  COMPLETED
  FAILED
}

enum WorkflowState {
  PENDING
  PROCESSING
  COMPLETED
  FAILED
}

input CheckoutInput {
  operationKey: ID!
  paymentMethod: PaymentMethod!
}

enum PaymentMethod {
  PIX
  CARD
}

type Query {
  checkout(id: ID!): CheckoutOperation
}

type Mutation {
  addToCart(productId: ID!, quantity: Int!): Cart!
  removeFromCart(productId: ID!, quantity: Int!): Cart!
  checkout(input: CheckoutInput!): Order!
}
