extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.11", import: ["@key", "@external", "@shareable"])

type CheckoutOperation @key(fields: "id") {
  id: ID!
  operationKey: ID!
  status: CheckoutStatus!
}

extend type Order @key(fields: "wooOrderId") {
  wooOrderId: ID! @external @shareable
  workflow: OrderWorkflow!
  pixCode: String
}

type OrderWorkflow {
  state: WorkflowState!
}

enum CheckoutStatus {
  PENDING
  COMPLETED
  FAILED
}

enum WorkflowState {
  PENDING
  PROCESSING
  COMPLETED
  FAILED
}

type Query {
  checkout(id: ID!): CheckoutOperation
}
