export { GraphqlOAuthResourceGuard } from './oauth-resource/graphql/oauth-resource.guard.ts';
export { OAuthSubject } from './oauth-resource/graphql/oauth-subject.decorator.ts';
export { RequireScopes } from './oauth-resource/graphql/require-scopes.decorator.ts';
export { OAuthResourceModule } from './oauth-resource/oauth-resource.module.ts';
export type { OAuthClaims } from './oauth-resource/domain/value-objects/oauth-claims.ts';
export type { OAuthGraphQLContext } from './oauth-resource/presentation/graphql/oauth-graphql-context.ts';
export type { OAuthHttpRequest } from './oauth-resource/infrastructure/http/oauth-http-request.ts';
export type { OAuthResourceOptions } from './oauth-resource/oauth-resource.types.ts';
export { OAuthRequestAdapter } from './oauth-resource/verification/oauth-request.adapter.ts';
export { OAuthCredentialError } from './oauth-resource/domain/errors/oauth-credential.error.ts';
export { OAuthAuthenticationMessages } from './oauth-resource/presentation/graphql/oauth-authentication-messages.ts';
export { OAuthResourceService } from './oauth-resource/verification/oauth-resource.service.ts';
