query getMyOrders($first: Int, $after: String) {
  customer {
    orders(first: $first, after: $after) {
      nodes {
        id
        status
        transactionId
        total
        currency
        lineItems {
          nodes {
            quantity
            product {
              id
              name
              price
            }
          }
        }
        paymentMethod
        workflow {
          state
        }
        pixCode
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
