export const ORDER_WORKFLOW_ORM = Symbol('ORDER_WORKFLOW_ORM');
export const ORDER_WORKFLOW_ENTITY_MANAGER = Symbol(
  'ORDER_WORKFLOW_ENTITY_MANAGER',
);
export const WOO_CHECKOUT = Symbol('WOO_CHECKOUT');
export const CHECKOUT_REPOSITORY = Symbol('CHECKOUT_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
